### ISSUE TITLE
Title: Inconsistency between the iterative proposed CoFiMA update and Fisher-weighted averaging

### ISSUE THREAD

**Issue by Yikai-Liao** [IemProg/CoFiMA#3]
Hi,

I’ve been reviewing the CoFiMA method, and I noticed an inconsistency between the description of the iterative update process and the actual formula provided in the paper.

![image](https://github.com/user-attachments/assets/18214020-744b-4f6e-9c69-813f2e2d842f)

Eq 7 is not  strictly equivalent to Eq 6, as it only considers the previous Fisher information matrix. It might lead to forget.

However, by simply accumulating the Fisher information matrix, we could get a version strictly equivalent to Eq 6.

I'm not sure why such update strategy hasn't been taken, is it for any particular reason?

**Comment by IemProg** [comment]
Hi @Yikai-Liao ,

Thank you for your interest in our paper and for taking the time to point out this aspect of the CoFiMA method. Your observation regarding the iterative update process and its relationship with the Fisher information matrix is valid, and I appreciate the opportunity to clarify our approach.

You are correct that Eq. (7) is not a strict equivalent of Eq. (6), as the Fisher matrix used in the update rule is for task \( t-1 \), rather than an accumulated version. This design choice is deliberate due to the nature of Fisher information matrices—since these matrices are estimated from different datasets for each task, directly accumulating them may not be entirely accurate or optimal for capturing task-specific information.

By recalculating Fisher matrices for each task’s data, we aim to retain the most relevant information for the corresponding task. The trade-off here is that our approach introduces an additional cost of storing the Fisher matrix for task \( t-1 \), as we hypothesize that this leads to better performance.

Please feel free to re-open the issue if you have any questions or concerns.
